###behaviorbot welcome - https://github.com/behaviorbot/

newIssueWelcomeComment: >
  Thanks for opening your first issue to the 2003page GitHub! Be sure to follow the issue template!

newPRWelcomeComment: >
  Thanks for opening this pull request! Please make a issue about your inviation request with the template.

firstPRMergeComment: >
  Congrats on merging your first pull request! We here at 2003page are proud of you!

###stale bot

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions. If this is a join request, then please resend your request.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
